### ISSUE TITLE
support for simpler 'pre'

### ISSUE THREAD

**Issue by tripodsan** [adobe/parcel-plugin-htl#20]
As mentioned in https://github.com/adobe/project-helix/issues/267, it should be super easy to write a `pre.js` without knowing the complexity of the pipeline.

### suggest:

pipeline autodetects pre in simple form like:
```
module.exports = function pre(payload) {
  payload.resource.time = `${new Date()}`;
}
```

**Comment by tripodsan** [comment]
This changed the signature of the pre functions. They can now come in various flavours.
Biggest difference is the removal of the `next()` function, since the async aspect can be covered with a Promise or `async`. The `secrets` was renamed to a more general `config` object, and the logger moved into this config.

Minmal
-------
```js
/**
 * Simple example of the 'pre' function that is executed before the HTML is rendered.
 * @param payload The current payload of processing pipeline
 * @param payload.resource The content resource
 */
function pre(payload) {
  payload.resource.time = `${new Date()}`;
}
```
With config (secrets and logger)
---------------------
```js
/**
 * Simple example of the 'pre' function that is executed before the HTML is rendered.
 * The config object contains a `logger` that ca be used to log debug, info and error messages.
 * @param payload The current payload of processing pipeline
 * @param [config] Additional config
 * @param [config.logger] The logger
 */
function pre(payload, config) {
  const log = config.logger;
  log.debug('[pre] setting time.');
  payload.resource.time = `${new Date()}`;
}
```
Using Promise
---------------
```js
/**
 * Example of the 'pre' function that returns a Promise.
 * @param payload The current payload of processing pipeline
 * @param config.logger The logger
 * @return {Promise} When resolved, continues the rendering pipeline
 */
function pre(payload, config) {
  const log = config.logger;

  log.debug('[pre] ready to set time.');
  return new Promise((resolve) => {
    log.debug('[pre] setting time.');
    payload.resource.time = `${new Date()}`;
    setTimeout(resolve, 1000);
  });
}
```

Using Async
------------
```js

/**
  * Waits until `time` has passed.
 */
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  })
}

/**
 * Example of the 'pre' function that is defined `async`.
 * @param payload The current payload of processing pipeline
 * @param config.logger The logger
 */
async function pre(payload, config) {
  const log = config.logger;
  log.debug('[pre] ready to set time.');

  await wait(1000);

  log.debug('[pre] setting time.');
  payload.resource.time = `${new Date()}`;
}
```

**Comment by trieloff** [comment]
@tripodsan I like it.

The only thing that gives me pause is the implied return value (or that you *have to* modify the arguments of the `pre` function. The linting rules we have set up for Helix would complain about it, and I'd say it is an antipattern, even though the pipeline implementation makes it safe.

In short: I'd prefer an explicit `return` for every `pre`.

**Comment by tripodsan** [comment]
> In short: I'd prefer an explicit return for every pre.

maybe, but it adds complexity that is not needed.

**Comment by trieloff** [comment]
Do we then want to disable https://eslint.org/docs/rules/no-param-reassign

if you don't like writing `return`, there are arrow functions for you, but I feel that we are straying to far from what is accepted as "good JavaScript" here, even if it is convenient.

**Comment by tripodsan** [comment]
> Do we then want to disable https://eslint.org/docs/rules/no-param-reassign

we cannot dictate the rules for the developer. but @davidnuescheler wanted the most simple `pre` that is possible, so that's that it is.

> if you don't like writing return, there are arrow functions for you..
no, it's not about not writing the return. we could add the `return payload`. but it doesn't matter.

**Comment by trieloff** [comment]
If there was a `pre` that would include `return payload` – would the current implementation even take it? Or is reassigning parameters the only way it works?

**Comment by tripodsan** [comment]
:-) it wouldn't work.. but we can add it.

**Comment by trieloff** [comment]
I think we should. 

The param-reassign trick is neat, but it will definitely rub some people the wrong way. Doing the expected thing with return values just makes it more usable.

**Comment by tripodsan** [comment]
ok. I'll create an issue...
