### ISSUE TITLE
Remove pipeline specifics from parcel plugin

### ISSUE THREAD

**Issue by tripodsan** [adobe/parcel-plugin-htl#22]
The current htl plugin is responsible for:
- turning the .htl into a javascript function that produces the html
- loading and executing the `pre.js` 
- loading the pipeline
- wrapping everything into an openwhisk action

The plugin should only be responsible to create the JS function, and the rest should be handled by `hlx build`. this allows to use other scripts like JST or simple transformers needed for JSON rendering. see https://github.com/adobe/helix-cli/issues/70

**Comment by tripodsan** [comment]
@trieloff how should we do this? on the one hand, I would like to remove the action specific stuff from the parcel plugin, otoh, we want to use the ability of parcel to package/bundle all that's needed into the JS. I see the following option:

we declare the generated template JS as `final`, so it is not further processed with parcel at the first stage of building. then in a 2nd stage we use parcel again to build the final action. so:

stage 1: pre-compile the templates into javascripts (htl -> js)
stage 2: bundle the action (html.js + html.pre.js + wrapper.js -> html-action.js)

maybe this would also solve the #16 problem.

**Comment by trieloff** [comment]
Having a two-step parcel process might be the best way to do it. It would also allow us to reap some additional benefits:

- you can write pure functions yourself, for instance if you don't need a templating language or want to generate JSON
- parcel-plugins for additional templating languages are simpler and more maintainable.

What I'm not sure about is how the process would run:
- do we have to run parcel twice?
- can we chain this as dependencies somehow?
- how to make sure that "our" JS post-processing doesn't conflict with Parcel's own?

**Comment by trieloff** [comment]
I'll be back at work on Monday, and we should chat about this then.

With the new `dist` behavior we might want to run multiple Parcel instances anyway:

1. for server-side template processing
2. for packaging scripts into OW actions
3. for turning client-side assets into `dist`-ready static assets.

**Comment by tripodsan** [comment]
> do we have to run parcel twice?

yes.

> can we chain this as dependencies somehow?
I tried to do this, but somehow the parcel processing chain doesn't really work for "custom" asset types. maybe using a different extension.

> how to make sure that "our" JS post-processing doesn't conflict with Parcel's own?

I think it doesn't (for stage 2) if we only specify the entry .js that need to be bundled into the action.

**Comment by trieloff** [comment]
One more thought that came up over the weekend. Modern frameworks like Gatsby have [route-based code splitting](https://www.gatsbyjs.org/blog/gatsby-v1/#route-based-code-splitting) out of the box.

We should make sure that we can support the same, i.e. that for a given page, we identify all the constituent server-side includes and their client-side dependencies. Then we allow depending on one bundle of client-side assets per template instead of having one per site.

**Comment by tripodsan** [comment]
yes...but it all depends on the "include-technology" (client side, esi, htl-include). especially, the last one would profit from this. (should we create a new issue for this topic?)

**Comment by trieloff** [comment]
Probably two issues:

1. htlengine to support ESI (the others can wait) (that way nobody has to write ESI statements again)
2. parcel-plugin-htl to build dependency tree based on htl-includes
